<Project Sdk="Microsoft.NET.Sdk">
 
 <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <IsPackable>false</IsPackable>
	 <Nullable>enable</Nullable>
	 <LangVersion>latest</LangVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.0" />
    <PackageReference Include="NLog.Windows.Forms" Version="6.1.4" />
    <PackageReference Include="OpenAC.Net.Core" Version="1.6.0" />
    <PackageReference Include="OpenAC.Net.DFe.Core" Version="1.7.0.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />
  </ItemGroup>
  
  <ItemGroup>
	<ProjectReference Include="..\OpenAC.Net.NFSe.DANFSe.PDFSharp\OpenAC.Net.NFSe.DANFSe.PDFSharp.csproj" />
	<ProjectReference Include="..\OpenAC.Net.NFSe\OpenAC.Net.NFSe.csproj" />
  </ItemGroup>
</Project>